name: "Reusable Workflow"
description: "Reusable steps"

inputs:
  cache-key:
    description: "Cache key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.3"

    - name: Restore the Cache
      id: cache
      uses: actions/cache@v4.0.2
      with:
        path: ./vendor
        key: ${{ inputs['cache-key'] }}

    - name: Composer Install
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        composer install

    - name: Create .env
      shell: bash
      run: |
        cp .env.ci .env
        cp .env.ci .env.testing

    - name: Generate the key
      shell: bash
      run: |
        php artisan key:generate
